parameters:
#    user_common.example.class: User\CommonBundle\Example

services:
#    user_common.example:
#        class: %user_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
