services:
   web.user.form.type.register:
       class: User\CommonBundle\Form\Type\RegisterType
       arguments: [@router]
       tags:
           - { name: form.type, alias: user_register_form }
   
