parameters:
#    web_page.example.class: Web\PageBundle\Example

services:
#    web_page.example:
#        class: %web_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
