parameters:
#    web_project.example.class: Web\ProjectBundle\Example

services:
#    web_project.example:
#        class: %web_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
